<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script type="text/javascript" src="views/jquery/js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="views/jquery/js/jquery-css-transform.js"></script>
<script type="text/javascript" src="views/jquery/js/rotate3Di-0.9.js"></script>


<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Language" content="en-us" />
<meta name="keywords" content="" />
<meta name="description" content="" />

<title>Virtual Lab</title>
<link href="views/styles.css" rel="stylesheet" type="text/css" />

</head>
<body>

<div style="height:100%;">
<!-- <img alt="" src="views/images/bg.jpg" id="background_image" /> -->
<div id="main">
	<div id="header">	
		<!--<div id="logo" ><div id="logo_strip"></div></div>  -->
		 <div id="logo_strip" style="padding-top: 5px;height: 50px;">

			<img alt="" src="views/images/vlab_banner_new.jpg" usemap="#banner" />
			<map name="banner" id="banner">
				<area alt="poly page" shape="rect" coords="0,0,142,52" href="http://www.poly.edu" />
				<area alt="" shape="rect" coords="143,1,870,52" href="https://vital.poly.edu/interim" />
				<area alt="" shape="rect" coords="871,1,1001,52" href="http://isis.poly.edu" />
			</map>
		
		</div>

				<div id="fillGap">

		</div>

			</div>
<!-- header ends -->

<!-- content begins -->
<div id="contop"></div>
<div id="content_bg">
  <div id="content">
	

  <table style="padding:2em; height:100%;">

  <tbody>
    <tr style="height:100%;">
      <td style="text-align: center; vertical-align: middle; width:65%;">
        <div id="vlab_page">
          <span style="font-size:large; color:black;">

            <b>Virtual Lab</b>
            <i>is a part of Information Systems and Internet
            Security Laboratory (ISIS) that provides remote access
            to the Information Assurance Lab facility in ISIS.</i>

          </span>

        </div>
        <table style="width:50%; height:94px; margin-left:auto; margin-right:auto; margin-top:15%;">
          <tbody>
            <tr>
              <td>
                <div class="logo" id="nsf_logo">
                  <img alt="NSF Logo"
                  src="views/images/nsf_logo.gif"
                  usemap="#nsf_map" />
                  <map name="nsf_map" id="nsf_map">
                    <area alt="NSF Home Page" shape="rect"
                    coords="0,0,48,48"
                    href="http://www.nsf.gov/" />

                  </map>
                </div>
              </td>
              <td>
                <div class="logo" id="cisco_logo">
                  <img alt="CISCO Logo"
                  src="views/images/cisco_logo.jpg"
                  usemap="#cisco_map" />
                  <map name="cisco_map" id="cisco_map">
                    <area alt="Cisco Home Page" shape="rect"
                    coords="0,0,48,48"
                    href="http://www.cisco.com/" />
                  </map>

                </div>
              </td>
              <td>
                <div class="logo" id="xen_logo">
                  <img alt="Xen Logo"
                  src="views/images/xen_logo_med.gif"
                  usemap="#xen_map" />
                  <map name="xen_map" id="xen_map">
                    <area alt="Xen Home Page" shape="rect"
                    coords="0,0,63,63"
                    href="http://www.xen.org/" />
                  </map>
                </div>

              </td>
              <td>
                <div class="logo" id="gentoo_logo">
                  <img alt="Gentoo Logo"
                  src="views/images/normal.jpg"
                  usemap="#gentoo_map" />
                  <map name="gentoo_map" id="gentoo_map">
                    <area alt="Gentoo Home Page" shape="rect"
                    coords="0,0,60,60"
                    href="http://www.gentoo.org/" />
                  </map>
                </div>
              </td>

            </tr>
          </tbody>
        </table>
      </td>
      <td style="border-left:1px solid gray; vertical-align: top; width:35%;">

        <div id="right">
	<a href="index.php"><font size='tiny' color='#FC4710'>admin page</font></a>
            <span id="registration_box" style="display:block;text-align:center;outline:2px solid #E8EEFA;border:3px solid #FFFFFF;padding:10px;margin:10px;background-color:#D8DEEA;border-radius:15px">

